### ISSUE TITLE
Which parameter should we tweak to get a BkdTree without using Disk

### ISSUE THREAD

**Issue by rsbala** [deepfabric/bkdtree#1]
Thanks for the library! Is there a way to use this BkdTree fully in memory for better performance skipping the disk overheads and also encoding/decoding overhead.

Any ways to tweak this like increasing t0M values or something?

**Comment by yuzhichang** [comment]
The BkdTree data-structure is designed for external storage. This Golang implementation use mmap to speedup file read/write. (However mmap cost much RAM. It's better to make mmap optional.)

There are some parameters to tweak for performance: t0mCap, leafCap, intraCap.
t0m is an array of points in RAM. 
leafCap is the capacity of a leaf node. Array under that size is not divided any more.
intraCap is the capacity of an internal node.
My benchmark doesn't show obvious difference of tweaking them.

**Comment by rsbala** [comment]
Thanks for the reply.
