### ISSUE TITLE
Does Intersect iterate over all points ?

### ISSUE THREAD

**Issue by rsbala** [deepfabric/bkdtree#2]
I see that Intersect iterates over all points in T0M and other Tis also. Is it expected ? Just wondering whether there is some bug. Please help.

I put a log line inside the for loop (for i := 0; i < pae.numPoints; i++) in intersectNode function in bkdtree_intersect.go. And I see the log getting printed N times where N is the total number of points inserted.

**Comment by yuzhichang** [comment]
Looks like a bug. intersectNode shall strip away children those are impossible in query range.
5ce0888b05c5b73739898cb0eeff3c767935bd1e fix this.

**Comment by rsbala** [comment]
Thanks for the fix :+1:
